#Playbook to ensure Apache is running with latest version
- name: Playbook name
  hosts: webservers  #hostgroup name
  become: yes
  become_user: root  #like sudo bash
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started