#install apache2
---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache2 pkg
      apt:
        name: apache2
        state: latest

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
        state: latest

# to run: ansible-playbook apache2_pb.yml --ask-become-pass apache2_playbook.yml
# to remove: cp apache2_pb.yml remove_apache.yml
   # change state: absent
   # run: ansible-playbook --ask-become-pass remove_apache.yml