#install apache2
---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache2 pkg
      apt:
        name: apache2

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php

# to run: ansible-playbook --ask-become-pass apache2_playbook.yml