#Header section
- name: Playbook Name
  hosts: target_hosts
  become: yes
  become_user: ubuntu
  gather_facts: yes

#Install MariaDB
- name: Install MariaDB on Ubuntu
  hosts: node1
  become: true
  tasks:
    - name: Update APT Package Cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

#Note... to run, use command: ansible-playbook sections_pb_example.yaml
#To check that MariaDB is installed, run: ansible node1 -m command -a "mariadb --version" -b